name: build cdt on windows

on:
  push:
    branches: [ debug ]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: windows-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     submodules: recursive
      #     fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
      - name: Checkout
        shell: msys2 {0}
        run: |
          pacman --noconfirm -S --needed base-devel mingw-w64-clang-x86_64-libc++
          pacman --noconfirm -S mingw-w64-clang-x86_64-libunwind
      - name: Copy dlls
        shell: msys2 {0}
        run: |
          echo $PATH
          cp /clang64/bin/libc++.dll libc++.dll
          cp /clang64/bin/libunwind.dll libunwind.dll
          ls *.dll
          rm *.dll
      - run: |
          set MSYSTEM=MSYS
          msys2 -c 'cp /clang64/bin/libc++.dll libc++.dll'
          msys2 -c 'cp /clang64/bin/libunwind.dll libunwind.dll'
          msys2 -c 'ls *.dll'
      # - name: Build cdt
      #   shell: msys2 {0}
      #   run: |
      #     mkdir build
      #     cd build
      #     cmake -G"Unix Makefiles" -DENABLE_NATIVE_COMPILER=OFF ..
      #     make -j $(nproc)
      # - name: generate release tarball
      #   shell: msys2 {0}
      #   run: |
      #     ./packages/generate_release.sh release-windows
      # - name: release-cdt
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       ./build/release-windows.tar.gz
